import { createConnection } from "typeorm";
import { ApolloServer } from "apollo-server";
import { typeDefs, resolvers } from "./schema";
import { createContext } from "./context";

const main = async () => {
  // Create a database connection.
  await createConnection();

  const server = new ApolloServer({
    typeDefs,
    // Because of a type issue between Apollo's definition of the Resolver map
    // and the one generated by graphql-code-generator we cast it to any.
    resolvers: resolvers as any,
    // We can pass our own context function in.
    // The context object will be passed to every resolver function and can be used to hold data like:
    //  - Authentication like JWT tokens or user session
    //  - Cache objects to be used during the request
    //  - ... anything else you'd like to pass to every resolver.
    context: ({ req }) => createContext(),
  });

  // Start the server.
  const serverInfo = await server.listen();
  console.log(`🚀 Server ready at ${serverInfo.url}`);
};

main().catch(err => {
  console.error(err);
  process.exit(1);
});
