import { createConnection } from "typeorm";
import { ApolloServer } from "apollo-server";
import { typeDefs, resolvers } from "./schema";

const main = async () => {
  // Create a database connection.
  await createConnection();

  const server = new ApolloServer({
    typeDefs,
    // Because of a type issue between Apollo's definition of the Resolver map
    // and the one generated by graphql-code-generator we cast it to any.
    resolvers: resolvers as any,
  });

  // Start the server.
  const serverInfo = await server.listen();
  console.log(`🚀 Server ready at ${serverInfo.url}`);
};

main().catch(err => {
  console.error(err);
  process.exit(1);
});
